dist: xenial
os: linux

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "12"

cache:
  directories:
     - ./node_modules

install:
  - npm ci

script:
  - npx ng lint
  - npm run-script build
  - npx ng test angular-rave -- --no-watch --no-progress --browsers=ChromeHeadlessCI

notifications:
  email: false